<?php

namespace Proxies\__CG__\Taller\Bundle\CursoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Curso extends \Taller\Bundle\CursoBundle\Entity\Curso implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setMateria(\Taller\Bundle\CursoBundle\Entity\Materia $materia = NULL)
    {
        $this->__load();
        return parent::setMateria($materia);
    }

    public function getMateria()
    {
        $this->__load();
        return parent::getMateria();
    }

    public function setAlumno(\Taller\Bundle\CursoBundle\Entity\Alumno $alumno = NULL)
    {
        $this->__load();
        return parent::setAlumno($alumno);
    }

    public function getAlumno()
    {
        $this->__load();
        return parent::getAlumno();
    }

    public function addAlumno(\Taller\Bundle\CursoBundle\Entity\Alumno $alumnos)
    {
        $this->__load();
        return parent::addAlumno($alumnos);
    }

    public function removeAlumno(\Taller\Bundle\CursoBundle\Entity\Alumno $alumnos)
    {
        $this->__load();
        return parent::removeAlumno($alumnos);
    }

    public function getAlumnos()
    {
        $this->__load();
        return parent::getAlumnos();
    }

    public function addMateria(\Taller\Bundle\CursoBundle\Entity\Curso $materias)
    {
        $this->__load();
        return parent::addMateria($materias);
    }

    public function removeMateria(\Taller\Bundle\CursoBundle\Entity\Curso $materias)
    {
        $this->__load();
        return parent::removeMateria($materias);
    }

    public function getMaterias()
    {
        $this->__load();
        return parent::getMaterias();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'alumnos', 'materias');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}